update sculptor, hardcode VF version
PaperMC/mache pull request #15
Opened 2024-04-05 06:46 UTC by Machine-Maker

Idea here is to create an issue when a build caused by an automated commit fails to either apply patches successfully or doesn't compile.

2024-04-06 02:14 UTC, Machine-Maker commented
Release sculptor version and update this PR to that version before merging

2024-04-08 07:36 UTC, MiniDigger commented on .github/workflows/deploy.yml
> +        run: ./gradlew ':versions:${{ needs.verify.outputs.project_name }}:publishMachePublicationToPaperMCRepository'
why did you remove the gradle build action here? and I guess we should add --no-daemon

2024-04-08 07:48 UTC, MiniDigger requested changes
see discord, lets move the auto updating logic to sculptor, including running the build and opening the issue (but lets keep deploy here in each branch, the running build twice is a fine)
that way we can easier update the auto updating, not having so much logic in each mache branch

2024-04-08 17:23 UTC, Machine-Maker commented on .github/workflows/deploy.yml
> +        run: ./gradlew ':versions:${{ needs.verify.outputs.project_name }}:publishMachePublicationToPaperMCRepository'
gradle build action is obsolete. It says to use setup-gradle and call the script directly. https://github.com/gradle/gradle-build-action

2024-04-08 18:37 UTC, closed without merging